DROP TABLE IF EXISTS VAT_RECORD;
DROP TABLE IF EXISTS TYPE;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS ITEM_TYPE;

CREATE TABLE VAT_RECORD (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    percentage REAL NOT NULL
);

CREATE TABLE TYPE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type TEXT NOT NULL,
    whitelisted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE ITEM (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    price REAL NOT NULL DEFAULT 0
);

CREATE TABLE ITEM_TYPE (
    item_id INTEGER NOT NULL,
    type_id INTEGER NOT NULL,
    FOREIGN KEY (item_id) REFERENCES ITEM(id),
    FOREIGN KEY (type_id) REFERENCES TYPE(id)
);

